# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 146)
        MainWindow.setMaximumSize(QtCore.QSize(500, 150))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.source_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.source_lineEdit.setReadOnly(True)
        self.source_lineEdit.setObjectName("source_lineEdit")
        self.horizontalLayout_3.addWidget(self.source_lineEdit)
        self.source_btn = QtWidgets.QToolButton(parent=self.centralwidget)
        self.source_btn.setObjectName("source_btn")
        self.horizontalLayout_3.addWidget(self.source_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dest_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dest_lineEdit.setReadOnly(True)
        self.dest_lineEdit.setObjectName("dest_lineEdit")
        self.horizontalLayout_4.addWidget(self.dest_lineEdit)
        self.dest_btn = QtWidgets.QToolButton(parent=self.centralwidget)
        self.dest_btn.setObjectName("dest_btn")
        self.horizontalLayout_4.addWidget(self.dest_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.convert_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.convert_pushButton.setObjectName("convert_pushButton")
        self.verticalLayout_2.addWidget(self.convert_pushButton)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VideoCompresser"))
        self.label.setText(_translate("MainWindow", "Source: "))
        self.source_btn.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Destination: "))
        self.dest_btn.setText(_translate("MainWindow", "..."))
        self.convert_pushButton.setText(_translate("MainWindow", "Convertir"))
